import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/* 
 * This program tests the reading of a text file (with 3 characters) generated by a batch file. 
 */
public class ReadInput {

	private int angle;
	public static final int DEFAULT_ANGLE = 90; //angles are represented as degrees to keep consistent with the input.
	
	//represents when the button is pressed, i.e. when to shoot
	protected static final int PRESSED = 999;
	
	private boolean shotOrNot;
	public static final boolean NORMAL = false;
	public static final boolean SHOT = true;
	
	public boolean isShotOrNot() {
		return shotOrNot;
	}

	public void setShotOrNot(boolean shotOrNot) {
		this.shotOrNot = shotOrNot;
	}

	public int getAngle() {
		return angle;
	}

	public void setAngle(int angle) {
		this.angle = angle;
	}

	public ReadInput(String fileName) { //fileName must be "fileName.txt" format
		
		//initialize
		setAngle(DEFAULT_ANGLE);
		setShotOrNot(NORMAL);
		
		File file = new File(fileName);
		
		try {
			Scanner scanner = new Scanner(file);
			
			if (scanner.hasNext()) { //if is used to read just one token. if doesn't work, then use while.
				
				int numInFile = Integer.parseInt(scanner.next());
				
				if (numInFile == PRESSED) { //if the number in the txt file is 999 
					setShotOrNot(SHOT);
				} else { //if the number in the txt file is not 999
					setAngle(numInFile);
				}
			}
			
			scanner.close();
			
		} catch (FileNotFoundException e) {
			System.out.println("Unable to open file " + fileName);
		} catch (NumberFormatException e) {
			System.out.println("Character in file " + fileName + " is not int.");
		}
		
	}
	
	public static void main(String[] args) {
		
		System.out.println(new ReadInput("input.txt").getAngle());
		
	}

}
